name: Build and Push Docker Image

on:
  push:
    branches:
      - main           # Dev publish
    tags:
      - 'v*.*.*'       # Release publish
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_ref: ${{ steps.build.outputs.image_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        id: build
        run: |
          # Temporary image tag for current build
          docker build -t temp-build:current .
          echo "::set-output name=image_ref::temp-build:current"

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image name and version
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          IMAGE=$(echo "$IMAGE" | sed 's/[^a-z-]//g')
          VERSION=${GITHUB_REF#refs/tags/}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION#v}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV

      - name: Retag and Push Release
        run: |
          TEMP_IMAGE=${{ needs.build.outputs.image_ref }}
          docker tag $TEMP_IMAGE $IMAGE:$VERSION
          docker tag $TEMP_IMAGE $IMAGE:v$MAJOR
          docker tag $TEMP_IMAGE $IMAGE:v$MAJOR.$MINOR
          docker tag $TEMP_IMAGE $IMAGE:latest

          docker push $IMAGE:$VERSION
          docker push $IMAGE:v$MAJOR
          docker push $IMAGE:v$MAJOR.$MINOR
          docker push $IMAGE:latest

  devpublish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image name
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          IMAGE=$(echo "$IMAGE" | sed 's/[^a-z-]//g')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Retag and Push Dev Image
        run: |
          TEMP_IMAGE=${{ needs.build.outputs.image_ref }}
          docker tag $TEMP_IMAGE $IMAGE:dev
          docker push $IMAGE:dev
